<h1>Numpy</h1>

In [9]:
import numpy as np

#se crea un np array de rango 1,
un_array = np.array([7, 77, 777, 1234])
print(type(un_array))

<class 'numpy.ndarray'>


In [10]:
print(type(un_array.shape))

print(un_array.shape)

print(un_array)

<class 'tuple'>
(4,)
[   7   77  777 1234]


In [11]:
# accediendo a las variables

print(un_array[0])
print(un_array[1])
print(un_array[2])
un_array[2] = 4
print(un_array[2])

7
77
777
4


In [14]:
otro = np.array([[5,10,15],[10,20,30],[20,40,60]])

print("la forma de este array es => ", otro.shape)


la forma de este array es =>  (3, 3)


In [16]:
#así se busca en el array
print(otro[1,1])
# así se imprime completo
print(otro)

20
[[ 5 10 15]
 [10 20 30]
 [20 40 60]]


$e^{i\pi} + 1 = 0$

$$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$

$ \frac{x^5-{7^{x+1}}}{2-x^2} $

$ I^{n \times n} =
\left( \begin{array}{cccc}
11 & 12 & 13 \\
22 & 23 & 24 \\
35 & 36 & 37 \\
\end{array} \right) $

<h1>Distintas maneras de crear nd arrays</h1>

In [23]:
# crear array lleno de ceros
ej1 = np.zeros((1080,1920))
print(ej1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
# creando un array lleno de un valor determinado (flats por ejemplos)
ej2 = np.full((2,2), 9.1)
print(ej2)

[[9.1 9.1]
 [9.1 9.1]]


In [47]:
#creando un array 2x2 condiagonal en "unos" y el resto cero
ej3 = np.eye(7,7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [31]:
#creandos arrays de unos
ej4 = np.ones((10,7,2))
print(ej4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [32]:
# creamos un array de flotantes aleatorios entre 0 y 1
ej5 = np.random.random((5,5))
print(ej5)

[[0.29565546 0.04349255 0.65762896 0.4633301  0.30702449]
 [0.15617622 0.16073781 0.51253589 0.3882338  0.31069828]
 [0.17845885 0.99000456 0.46435615 0.00742865 0.58322023]
 [0.82271399 0.01368704 0.96757575 0.18353372 0.83313702]
 [0.06732017 0.66924262 0.53946224 0.96273392 0.49802463]]


<h1>Array de índices</h1>

In [33]:
#creamos otro array
array_a = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [35]:
#creamos 2 arrays con números enteros que usaremos como indices
cols = np.array([0,1,2,0])
rows = np.arange(4)
print("Indices para filas", rows)
print("Indices para columnas", cols)

Indices para filas [0 1 2 3]
Indices para columnas [0 1 2 0]


In [36]:
#imprimimos los indices tomando uno de cada array  de rows y cols
for row,col in zip(rows,cols):
    print("==", row, "==", col, "==")

== 0 == 0 ==
== 1 == 1 ==
== 2 == 2 ==
== 3 == 0 ==


In [38]:
# los valores de cada fila en el array_a usando rows y cols
print("para imprimir contenido en los indices del array_a son: ", array_a[rows,cols])

para imprimir contenido en los indices del array_a son:  [11 22 33 41]


In [39]:
#operar con los valores seleccionados
print(array_a)
array_a[rows,cols] += 1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


<h1>Indexando Booleano</h1>
<h4>Indexando Booleano para cambiar elementos</h4>

In [40]:
#creamos un array de 3x2
array_b = np.array([[11,12], [21, 22], [31,32]])
print(array_b)
print("__________")
print(array_b.shape)


[[11 12]
 [21 22]
 [31 32]]
__________
(3, 2)


In [42]:
#crear un filtro es muy facil en numpy
filtro = (array_b > 15)
print(filtro)

[[False False]
 [ True  True]
 [ True  True]]


In [43]:
#entonces ahora podemos aplicar el fitro a nuestro array
filtrado = array_b[filtro]
print(filtrado)

[21 22 31 32]


In [45]:
#no es necesario primero crear el filtro y luego aplicarlo, podemos hacerlo al unísono
print(array_b[(array_b % 2== 0)])
print(array_b[array_b > 15])

[12 22 32]
[21 22 31 32]


<h3>El uso principal de este tipo de filtros es poder modificar los valores del array que cumplan con cierto criterio</h3>

In [48]:
array_b[array_b % 2 == 0] += 1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


<h1>Cortando los Arrays (Slice)</h1>
<h4>Sirve para aislar una "rub-region" de la matriz de un ndarray</h4>

In [82]:
un_array = np.array([[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35], [41,42,43,44,45]])
print(un_array)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [83]:
#creamos un_slice de 2x2 a partir de un_array
un_slice = un_array[1:3,1:3]
print(un_slice)

[[22 23]
 [32 33]]


In [84]:
#imprimimos el valor fila 0 columna 0 del slice
#como vemos enla salida, el slice genera un nuevo indice
print("slice: ", un_slice[0,0])

slice:  22


In [85]:
#ahora sumaremos 100 al valor de la posicion (0,0) del indice
#ahora veremos como podremos sumar sin problema alguno
un_slice[0,0] += 100
print("slice: ", un_slice[0,0])

slice:  122


In [86]:
#ahora imprimimos la posición (0,1) del array original
print("Array original: ", un_array[1,1])

Array original:  122


<h4>¡¡¡Los array originales se modifican!!!</h4>

In [87]:
#confirmamos el array original
print(un_array)

[[ 11  12  13  14  15]
 [ 21 122  23  24  25]
 [ 31  32  33  34  35]
 [ 41  42  43  44  45]]


<h2>Importante</h2>
<h4>Si quieres crear un nuevo array araiz del un_slice...</h4>

In [88]:
nuevo_array = np.array(un_slice)
print(nuevo_array)

[[122  23]
 [ 32  33]]


In [99]:
#para forzar el typo de data hay que añadirlo alfinal con dtype=np.float64 or dtype=np.int64
ejem1 = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float64)
print(ejem1.dtype)
print(ejem1)

float64
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [100]:
ejem2 = np.array([[1.2,2.3,3.4,4.5],[5.6,6.7,7.8,8.9]], dtype=np.int64)
print(ejem2.dtype)
print(ejem2)

int64
[[1 2 3 4]
 [5 6 7 8]]


In [111]:
#generar numeros aleatorios en un array
arr = 2 + np.random.randn(2,5)
print(arr)

[[2.28104601 2.71093016 0.71390093 2.57796847 2.21415636]
 [2.2211738  2.53181828 2.53000237 2.15248449 3.43441652]]


In [112]:
#calcular el promedio de un array
print(arr.mean())

2.336789736959178


In [114]:
#calcular promedio fila por fila
#eje de 0 = columnas (eje de y)
#eje de 1 = filas (eje de x)
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

[2.2511099  2.62137422 1.62195165 2.36522648 2.82428644]
[2.09960038 2.57397909]


In [115]:
#creamos arrays de dies elementos aleatorios
desordenado = np.random.randn(10)
print(desordenado)

[ 0.69557583  0.05308372  0.84371665 -1.12960393 -0.48876017 -0.59208411
 -1.18992018 -1.02500907 -0.43643052  0.01743687]


In [116]:
#creamos una copia
ordenado = np.array(desordenado)
# lo ordenamos
ordenado.sort()
print(ordenado)


[-1.18992018 -1.12960393 -1.02500907 -0.59208411 -0.48876017 -0.43643052
  0.01743687  0.05308372  0.69557583  0.84371665]


In [118]:
#buscando elementos unicos
array123 = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array123))


[1 2 4]


In [119]:
#operaciones de conjunto
n1 = np.array(["escritorio", "silla", "mesa"])
n2 = np.array(["escritorio", "silla", "lampara"])
print(n1)
print(n2)

['escritorio' 'silla' 'mesa']
['escritorio' 'silla' 'lampara']


In [122]:
#intersección
print( np.intersect1d (n1, n2) )

['escritorio' 'silla']


In [124]:
#union en 1d (se unen todos los elementos que no se repitan)
print(np.union1d(n1,n2))

['escritorio' 'lampara' 'mesa' 'silla']


In [127]:
#elementos de n1 que no están en el n2 o viceversa
print(np.setdiff1d(n1,n2))
print(np.setdiff1d(n2,n1))

['mesa']
['lampara']


In [128]:
#elementos del n1 que si están en el n2
print(np.in1d(n1,n2))

[ True  True False]


<h2>Operaciones Frecuentes</h2>

In [131]:
#sumamos todos los elementos de un array
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))
print(ex1)

66
[[11 12]
 [21 22]]


In [130]:
#sumamos las columnas eje 0
print(np.sum(ex1, axis=0))
##sumamos las filas eje 1
print(np.sum(ex1, axis=1))

[32 34]
[23 43]


<h4>Reformateando un array (importante)</h4>

In [132]:
#creamos un array
arr5 = np.arange(20)
print(arr5)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(2, 5)

In [141]:
#cambiamos su forma
reshaped_arr5 = arr5.reshape(4,5)
print(reshaped_arr5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [146]:
#transponer o transposicionar un array
ex5 = np.array([[11,12],[21,22]])
print(ex5)
ex5.T

[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [147]:
#where ... Muy útil
mat = np.random.rand(4,4)
mat

array([[0.13712028, 0.22282672, 0.62965418, 0.78385776],
       [0.46032394, 0.31234048, 0.06738483, 0.08971854],
       [0.92046147, 0.84143929, 0.85121703, 0.48393575],
       [0.42339046, 0.96607448, 0.61424789, 0.7877312 ]])

In [150]:
#le paso array con condición, pones valor si True, Pones valor si False
np.where(mat > 0.5, 1000, -1)

array([[  -1,   -1, 1000, 1000],
       [  -1,   -1,   -1,   -1],
       [1000, 1000, 1000,   -1],
       [  -1, 1000, 1000, 1000]])

In [158]:
#comprobar si algun elemento del array es True, no importa si son numeros o boleanos
arr_bools = np.array([0,0,1,True,0,False])
arr_bools.any()

True

In [167]:
#comprobar si todos los elementos son True
arr_bools = np.array([1,1,1])
arr_bools.all()

False

<h3>Uniendo Data Sets</h3>

In [169]:
k = np.random.randint(low=2, high=50, size=(2,2))
print(k)

m = np.random.randint(low=2, high=50, size=(2,2))
print(m)

[[25 12]
 [46 47]]
[[ 4 45]
 [29 48]]


In [171]:
#uniendo vertivalmente
np.vstack((k,m))

array([[25, 12],
       [46, 47],
       [ 4, 45],
       [29, 48]])

In [172]:
#uniendo horizontalmente
np.hstack((k,m))

array([[25, 12,  4, 45],
       [46, 47, 29, 48]])

In [173]:
#uniendo vertivalmente
np.concatenate([k,m], axis = 0)

array([[25, 12],
       [46, 47],
       [ 4, 45],
       [29, 48]])

In [174]:
#uniendo horizontalmente
np.concatenate([k,m], axis = 1)

array([[25, 12,  4, 45],
       [46, 47, 29, 48]])

<h2>Propagación</h2>

In [180]:
base = np.zeros((4,4))
print(base)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [181]:
row = np.array([1,0,2,7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [183]:
#propagación lateral
y = base + row
print(y)

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [188]:
#ahora para la propagación horizontal
col = np.array([[0,1,2,3]])
print(col)

[[0 1 2 3]]


In [189]:
#se transpone la fila en columna
col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [190]:
y = base + col
print(y)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [191]:
arr_x = np.array([1])
print(arr_x)
print("___________")
y = arr_x + base
print(y)

[1]
___________
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<h1>Grabar array a disco y recuperarlo del disco</h1>

In [198]:
M = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])

In [199]:
np.save("array_para guardar", M)

In [200]:
recuperar = np.load("array_para guardar.npy")
print("el array recuperado es: ", recuperar)

el array recuperado es:  [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
